// Generated by CoffeeScript 1.6.3
(function() {
  var NG_OPTIONS_REGEXP, app;

  app = angular.module('selectize', []);

  NG_OPTIONS_REGEXP = /^\s*([\s\S]+?)(?:\s+as\s+([\s\S]+?))?(?:\s+group\s+by\s+([\s\S]+?))?\s+for\s+(?:([\$\w][\$\w]*)|(?:\(\s*([\$\w][\$\w]*)\s*,\s*([\$\w][\$\w]*)\s*\)))\s+in\s+([\s\S]+?)(?:\s+track\s+by\s+([\s\S]+?))?$/;

  app.directive('selectize', function($parse) {
    return {
      require: '?ngModel',
      link: function(scope, element, attributes, ngModel) {
        var match, optionsExp;
        optionsExp = attributes.selectize;
        match = optionsExp.match(NG_OPTIONS_REGEXP);
        return element.selectize({
          valueField: 'id',
          labelField: 'title',
          searchField: ['title'],
          options: [
            {
              'id': 'yes',
              'title': 'yes'
            }, {
              'id': 'no',
              'title': 'no'
            }, {
              'id': 'maybe',
              'title': 'maybe'
            }
          ],
          create: false
        });
      }
    };
  });

}).call(this);
