// Generated by CoffeeScript 1.6.3
(function() {
  var NG_OPTIONS_REGEXP, app;

  app = angular.module('selectize', []);

  NG_OPTIONS_REGEXP = /^\s*([\s\S]+?)(?:\s+as\s+([\s\S]+?))?(?:\s+group\s+by\s+([\s\S]+?))?\s+for\s+(?:([\$\w][\$\w]*)|(?:\(\s*([\$\w][\$\w]*)\s*,\s*([\$\w][\$\w]*)\s*\)))\s+in\s+([\s\S]+?)(?:\s+track\s+by\s+([\s\S]+?))?$/;

  app.directive('selectize', function($parse) {
    return {
      require: '?ngModel',
      link: function(scope, element, attributes, ngModel) {
        var displayFn, groupByFn, keyName, match, optionsExp, track, trackFn, valueFn, valueName, valuesFn;
        optionsExp = attributes.selectize;
        match = optionsExp.match(NG_OPTIONS_REGEXP);
        displayFn = $parse(match[2] || match[1]);
        valueName = match[4] || match[6];
        keyName = match[5];
        groupByFn = $parse(match[3] || "");
        valueFn = $parse((match[2] ? match[1] : valueName));
        valuesFn = $parse(match[7]);
        track = match[8];
        trackFn = (track ? $parse(match[8]) : null);
        element.selectize({
          valueField: 'id',
          labelField: 'title',
          searchField: ['title'],
          options: [
            {
              'id': 'yes',
              'title': 'yes'
            }, {
              'id': 'no',
              'title': 'no'
            }, {
              'id': 'maybe',
              'title': 'maybe'
            }
          ],
          create: false
        });
        element.on('change', function() {
          return scope.$apply(function() {
            return ngModel.$setViewValue(element.val());
          });
        });
        return ngModel.$render = function() {
          return element.setValue(ngModel.$viewValue);
        };
      }
    };
  });

}).call(this);
